import Navbar from "../components/Navbar";
export const metadata = {
  title: "Lexardi | Product",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
